name: CI

on:
  push:

jobs:
  static-analysis:  # black, mypy, ruff  정적 분석
    runs-on: ubuntu-22.04
    steps:
      - name: "Check out th codes"
        uses: actions/checkout@v2

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v4
        with:
          key: poetry-1.8.5
          path: ~/.local/

      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.8.5

      - name: Register Poetry bin
        run: echo "${HOME}/.local/bin/" >> %GITHUB_PATH

      - name: Cache dependencies
        id: cache-venv
        uses: actions/cache@v4
        with:
          key: python-${{ steps.setup-python.outputs.python-version }}-poetry-lock-${{ hashFiles('poetry.lock') }}-toml-${{ hashFiles('pyproject.toml') }}-poetry-1.8.5
          path: /home/runner/.cache/pypoetry/virtualenvs/

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: poetry install --no-root

      - name: Run Black
        run: poetry run black . --check

      - name: Run Ruff
        run: |
          poetry run ruff check --select I
          poetry run ruff check

      - name: Run Mypy
        run: poetry run mypy .

  test:  # 전체 테스트 실행함
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codes
        uses: actions/checkout@v2

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v4
        with:
          key: poetry-1.8.5
          path: ~/.local/

      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.8.5

      - name: Register Poetry bin
        run: echo "${HOME}/.local/bin/" >> $GITHUB_PATH

      - name: Cache dependencies
        id: cache-venv
        uses: actions/cache@v4
        with:
          key: python-${{ steps.setup-python.outputs.python-version }}-poetry-lock-${{ hashFiles('poetry.lock') }}-toml-${{ hashFiles('pyproject.toml') }}-poetry-1.8.5
          path: /home/runner/.cache/pypoetry/virtualenvs/

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: poetry install --no-root

      - name: Cache Gel CLI
        id: cache-gel
        uses: actions/cache@v4
        with:
          path: ~/.gel/bin
          key: ${{ runner.os }}-gel-cli

      - name: Install Gel CLI
        if: steps.cache-gel.outputs.cache-hit != 'true'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://get.gel.run | sh -s -- -y

      - name: Cache Gel Server Binaries
        uses: actions/cache@v4
        with:
          # 경로를 ~/.local/share/gel 로 변경합니다.
          path: |
            ~/.local/share/gel
            ~/.cache/gel
          key: ${{ runner.os }}-gel-server-${{ hashFiles('gel.toml') }}
          restore-keys: |
            ${{ runner.os }}-gel-server-

      - name: Setup Gel Instance
        run: |
          poetry run gel instance create test_instance --tls-security=insecure || echo "Instance already exists"
          poetry run gel project init --non-interactive --server-instance test_instance --link

      - name: Run tests
        run: |
          poetry run coverage run -m pytest .
          poetry run coverage report -m
      
      
      
    
    
    
      
      
      

